### ISSUE TITLE
getResult(): Return value must be of type string, null returned

### ISSUE THREAD

**Issue by xomorg** [nsu-soft/yii-dadata#16]
При попытке распознать адрес, введённый, например, в ошибочно раскладке, возникает ошибка

TypeError: nsusoft\dadata\types\direct\clean\CleanAddressDirect::getResult(): Return value must be of type string, null returned in /var/www/uis0/priem.nsu.ru/www/vendor/nsu-soft/yii-dadata/src/types/direct/clean/CleanAddressDirect.php:28

Версия: 0.3.1

**Comment by vommuan** [comment]
Спасибо за обратную связь. Ошибка исправлена. Проверяйте.
